apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blue-green
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/ksnithya/blue-green.git
